In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [3]:
ar = np.array(a)
ar

array([1, 2, 3, 4, 5])

In [4]:
ar = np.array([1, 2, 3, 4, 5])
ar

array([1, 2, 3, 4, 5])

In [5]:
ar = np.array({1, 2, 3, 4, 5})
ar

array({1, 2, 3, 4, 5}, dtype=object)

In [8]:
ar = np.arange(1, 201)
ar

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [10]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
amatrix = np.array(matrix)
amatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
lst2 = []
for i in range(1, 201):
    lst2.append(i)
sum(lst2)/len(lst2)

100.5

In [18]:
arr = np.array(lst2)
np.mean(arr)

100.5

In [21]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
ar = np.array(matrix)
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
ar.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [30]:
all_zero = np.ones([10, 5])
all_zero

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
arr = np.linspace(0, 2, 3)
arr

array([0., 1., 2.])